services:
  - type: web
    name: spite-backend
    env: docker
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    dockerfilePath: ./Dockerfile
