spring.application.name=spite-backend
server.address=0.0.0.0
server.port=8080

spring.data.mongodb.uri=mongodb+srv://spiteuser:spiteuser@cluster0.xj3uvla.mongodb.net/spite
spring.data.mongodb.database=spite

# spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
# spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}

spring.web.resources.static-locations=classpath:/static/

# cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
# cloudinary.api_key=${CLOUDINARY_API_KEY}
# cloudinary.api_secret=${CLOUDINARY_API_SECRET}

cloudinary.cloud_name=dth0muz7n
cloudinary.api_key=372544964785764
cloudinary.api_secret=DUJZTI2pYC_Rzs-96q1i-5_TfyM



spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
